import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from migration_factory_plugin_mcp.graph import schema, tree as tree_mod, valuesfile  # noqa: E402


def _build_fixture():
    company = tree_mod.Actor(id="company-1", title="ACME", form_id=1, picture="logo.png")
    employee = tree_mod.Actor(
        id="emp-1", title="Employee #1", description="hired 2024", form_id=2,
        position=tree_mod.Position(x=0, y=0),
    )
    f = tree_mod.File(
        layer_id="layer-1",
        actors=[company, employee],
        edges=[tree_mod.Edge(source="company-1", target="emp-1")],
    )
    tree, warnings = tree_mod.build_tree(f)
    assert warnings == []

    types = schema.TypeSet(types=[
        schema.Type(slug="company", form_id=1, fields=[
            schema.FieldSpec(name="industry", id="industry", type="string"),
        ]),
        schema.Type(slug="employee", form_id=2, fields=[
            schema.FieldSpec(name="role", id="role", type="string"),
        ]),
    ])

    values = {
        "company-1": {"industry": "Manufacturing"},
        "emp-1": {"role": "CFO", "unlisted_field": "extra"},
    }
    return tree, types, values


def test_render_values_shape():
    tree, types, values = _build_fixture()
    rendered = valuesfile.render_values(tree, types, values).decode("utf-8")

    assert rendered.startswith("# generated by migration-factory-plugin-mcp")
    assert "layer: layer-1\n" in rendered
    assert "tree: |\n" in rendered
    assert "pictures: |\n" in rendered

    lines = rendered.splitlines()
    tree_start = lines.index("tree: |") + 1
    # Root node at depth 0 -> 2-space indent.
    assert lines[tree_start] == "  ACME [company]"
    assert lines[tree_start + 1] == "    industry: Manufacturing"
    # Child node at depth 1 -> 4-space indent, description as trailing comment.
    assert lines[tree_start + 2] == "    Employee #1 [employee]  # hired 2024"
    # Schema field first, then the unlisted field alphabetically after.
    assert lines[tree_start + 3] == "      role: CFO"
    assert lines[tree_start + 4] == "      unlisted_field: extra"

    pictures_idx = rendered.index("pictures: |")
    pictures_block = rendered[pictures_idx:]
    assert "  ACME" in pictures_block  # only the pictured node is listed


def test_render_values_pictures_block_present_even_when_empty():
    tree, types, values = _build_fixture()
    for actor in (tree.nodes["company-1"].actor, tree.nodes["emp-1"].actor):
        actor.picture = ""
    rendered = valuesfile.render_values(tree, types, values).decode("utf-8")
    assert "pictures: |" in rendered


def test_format_value_dispatch():
    assert valuesfile._format_value(None) == ""
    assert valuesfile._format_value(True) == "true"
    assert valuesfile._format_value(False) == "false"
    assert valuesfile._format_value("  a   b  ") == "a b"
    assert valuesfile._format_value(3) == "3"
    assert valuesfile._format_value(3.5) == "3.5"
    assert valuesfile._format_value(3.0) == "3"
    assert valuesfile._format_value({"title": "Some Ref"}) == "Some Ref"
    assert valuesfile._format_value(["a", "b", "c"]) == "a, b, c"


def test_values_looked_up_by_raw_field_id_rendered_under_slug():
    # A field whose Simulator id is opaque (item_<digits>) and whose schema
    # slug differs from it entirely — the values dict (clean_values' output)
    # is keyed by the raw id, and this must still render under the slug.
    employee = tree_mod.Actor(id="emp-1", title="Employee #1", form_id=2)
    f = tree_mod.File(layer_id="layer-1", actors=[employee], edges=[])
    tree, _ = tree_mod.build_tree(f)
    types = schema.TypeSet(types=[
        schema.Type(slug="employee", form_id=2, fields=[
            schema.FieldSpec(name="role", id="item_998877", type="string"),
        ]),
    ])
    values = {"emp-1": {"item_998877": "CFO"}}
    rendered = valuesfile.render_values(tree, types, values).decode("utf-8")
    lines = rendered.splitlines()
    tree_start = lines.index("tree: |") + 1
    assert lines[tree_start] == "  Employee #1 [employee]"
    assert lines[tree_start + 1] == "    role: CFO"


def test_depth_from_parent_chain_not_path_text():
    # A title containing the path separator itself must not corrupt
    # indentation depth.
    tricky = tree_mod.Actor(id="tricky-1", title="A > B", form_id=1)
    child = tree_mod.Actor(id="child-1", title="Child", form_id=2)
    f = tree_mod.File(
        layer_id="layer-1",
        actors=[tricky, child],
        edges=[tree_mod.Edge(source="tricky-1", target="child-1")],
    )
    tree, _ = tree_mod.build_tree(f)
    types = schema.TypeSet(types=[schema.Type(slug="t", form_id=1), schema.Type(slug="c", form_id=2)])
    rendered = valuesfile.render_values(tree, types, {}).decode("utf-8")
    lines = rendered.splitlines()
    tree_start = lines.index("tree: |") + 1
    assert lines[tree_start] == "  A > B [t]"
    assert lines[tree_start + 1] == "    Child [c]"
