"""types.schema.yaml — the field dictionary an export writes and an ops file
addresses types against. Rewritten on every export; a human edits the forms
in Simulator, not this file.

Unlike graph.values.yaml (a custom line grammar in a block scalar, see
valuesfile.py), this file is ordinary structured YAML — parseable by any
compliant reader regardless of exact formatting choices, so this module
prioritizes valid, round-trippable output over byte-identical rendering.
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field
from typing import Optional

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

TYPES_FILE_NAME = "types.schema.yaml"

TYPE_STRING = "string"
TYPE_TEXT = "text"
TYPE_INT = "int"
TYPE_NUMBER = "number"
TYPE_BOOL = "bool"
TYPE_DATE = "date"

_HEADER = """\
# Type dictionary for layer {layer_id} — generated by migration-factory-plugin-mcp.
# Rewritten on every export: change the forms in Simulator, not this file.
#
#   slug      what the map addresses a type by; derived from the form title
#   fields    <slug>: {{id: <simulator field id>, type: ..., writable: bool}}
#   types     string | text | int | number | bool | date | enum[...] | ref(<slug>)

"""


@dataclass
class FieldSpec:
    name: str  # the slug key a write addresses
    id: str  # Simulator field id ("item_<digits>" when opaque)
    type: str = TYPE_STRING
    title: str = ""
    writable: bool = True


@dataclass
class Type:
    slug: str
    form_id: int
    form_title: str = ""
    description: str = ""
    fields: list = field(default_factory=list)  # list[FieldSpec]

    def field_by_id(self, field_id: str) -> Optional[FieldSpec]:
        for f in self.fields:
            if f.id == field_id:
                return f
        return None


@dataclass
class TypeSet:
    types: list = field(default_factory=list)  # list[Type]

    def __post_init__(self):
        self._by_form = {t.form_id: t for t in self.types}
        self._by_slug = {t.slug: t for t in self.types}

    def type_by_form(self, form_id: int) -> Optional[Type]:
        return self._by_form.get(form_id)

    def by_slug(self, slug: str) -> Optional[Type]:
        return self._by_slug.get(slug)

    def slugs(self) -> list:
        return sorted(self._by_slug.keys())

    def slug_for_form(self, form_id: int) -> str:
        t = self._by_form.get(form_id)
        return t.slug if t else f"form_{form_id}"


def _yaml() -> YAML:
    # Round-trip mode (not "safe") because rendering needs to represent
    # CommentedMap with per-field flow style; round-trip loading of a plain
    # document works the same as safe loading for our purposes.
    y = YAML(typ="rt")
    y.default_flow_style = False
    return y


def _one_line(s: str) -> str:
    return " ".join(s.split())


def render_types_schema(layer_id: str, types: TypeSet) -> bytes:
    ordered = sorted(types.types, key=lambda t: t.form_id)
    doc = CommentedMap()
    types_map = CommentedMap()
    for t in ordered:
        entry = CommentedMap()
        entry["formId"] = t.form_id
        entry["form"] = t.form_title
        if t.description:
            entry["description"] = _one_line(t.description)
        fields_map = CommentedMap()
        for f in t.fields:
            spec = CommentedMap()
            spec["id"] = f.id
            spec["type"] = f.type
            if not f.writable:
                spec["writable"] = False
            if f.title:
                spec["title"] = _one_line(f.title)
            spec.fa.set_flow_style()
            fields_map[f.name] = spec
        entry["fields"] = fields_map
        types_map[t.slug] = entry
    doc["types"] = types_map

    y = _yaml()
    buf = io.StringIO()
    buf.write(_HEADER.format(layer_id=layer_id))
    y.dump(doc, buf)
    return buf.getvalue().encode("utf-8")


def parse_types_schema(data: bytes) -> TypeSet:
    y = _yaml()
    doc = y.load(io.BytesIO(data)) or {}
    raw_types = doc.get("types") or {}

    types: list = []
    seen_form_ids: dict = {}
    for slug, raw_type in raw_types.items():
        raw_type = raw_type or {}
        form_id = raw_type.get("formId")
        if not isinstance(form_id, int) or form_id <= 0:
            raise ValueError(f"type {slug!r}: formId is required and must be a positive integer")
        if form_id in seen_form_ids:
            raise ValueError(
                f"types {seen_form_ids[form_id]!r} and {slug!r} both map to formId {form_id} — "
                "a form has exactly one slug"
            )
        seen_form_ids[form_id] = slug

        fields: list = []
        for name, raw_field in (raw_type.get("fields") or {}).items():
            raw_field = raw_field or {}
            fields.append(
                FieldSpec(
                    name=name,
                    id=str(raw_field.get("id", name) or name),
                    type=str(raw_field.get("type", TYPE_STRING) or TYPE_STRING),
                    title=str(raw_field.get("title", "") or ""),
                    writable=bool(raw_field.get("writable", True)),
                )
            )
        # Field order is not preserved through the dict decode step in the Go
        # original (a map there); sorting by name keeps two plans of the same
        # file identical regardless of the source file's own field order.
        fields.sort(key=lambda f: f.name)

        types.append(
            Type(
                slug=slug,
                form_id=form_id,
                form_title=str(raw_type.get("form", "") or ""),
                description=str(raw_type.get("description", "") or ""),
                fields=fields,
            )
        )
    return TypeSet(types=types)


def load_types_schema(dir_path: str) -> "tuple[Optional[TypeSet], bool]":
    """Returns (type_set, found). found=False on ENOENT — not an error."""
    import os

    path = os.path.join(dir_path, TYPES_FILE_NAME)
    try:
        with open(path, "rb") as f:
            data = f.read()
    except FileNotFoundError:
        return None, False
    return parse_types_schema(data), True
