"""graph.values.yaml — the layer as a tree, with every stored value under its
node. Only the outer ``layer:``/``tree:``/``pictures:`` keys are ordinary
YAML; the ``tree:`` and ``pictures:`` VALUES are block-scalar TEXT with a
private line grammar this module owns both ends of (render here, parsed back
only as text by a human/LLM — nothing re-parses the tree's hierarchy from
this file; graph.ids.json is the machine-readable path index).
"""
from __future__ import annotations

import json
from typing import Any

from .schema import TypeSet
from .tree import Tree

VALUES_FILE_NAME = "graph.values.yaml"

_HEADER = """\
# generated by migration-factory-plugin-mcp (internal/graph) — do not edit by hand
# the layer as a tree, with every field value under its node
# addressing: any unique suffix of the path, separator " > "
# to write back: an ops file of `at:` + `set:`/`rename:`, addressed the same
# way — see graph.ops.yaml; `make live-apply OPS=<file>` prints the diff
# field names and [types]: see types.schema.yaml
# `pictures:` after the tree lists the nodes that already carry an image
layer: {layer_id}

"""

_PICTURES_HEADER = (
    "# nodes that already carry an image; every other node has none, and a run\n"
    "# fills those and replaces none of these\n"
)

Values = dict  # actor_id -> {field_key: value}


def _one_line(s: str) -> str:
    return " ".join(s.split())


def _label_of(m: dict) -> str:
    for key in ("title", "name", "label", "value"):
        v = m.get(key)
        if isinstance(v, str) and v:
            return v
    return json.dumps(m, ensure_ascii=False, sort_keys=True)


def _format_value(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return _one_line(v)
    if isinstance(v, float):
        # Shortest round-tripping representation, matching Go's
        # strconv.FormatFloat(v, 'f', -1, 64) intent: no scientific notation,
        # no forced trailing zeros.
        text = repr(v)
        if text.endswith(".0"):
            text = text[:-2]
        return text
    if isinstance(v, int):
        return str(v)
    if isinstance(v, dict):
        return _one_line(_label_of(v))
    if isinstance(v, list):
        return ", ".join(_format_value(item) for item in v)
    return _one_line(json.dumps(v, ensure_ascii=False))


def _depth_indent(depth: int) -> str:
    return "  " + "  " * depth


def _node_line(node, types: TypeSet) -> str:
    slug = types.slug_for_form(node.actor.form_id)
    line = f"{node.label} [{slug}]"
    if node.actor.description.strip():
        line += "  # " + _one_line(node.actor.description)
    return line


def _value_lines(node, types: TypeSet, values: Values) -> list:
    data = values.get(node.id) or {}
    if not data:
        return []
    t = types.type_by_form(node.actor.form_id)
    schema_fields = t.fields if t else []
    # Values are keyed by the raw Simulator field id (clean_values() already
    # normalized any "__form__<formId>:" prefix down to the bare id) — NOT by
    # the schema's human-readable slug (FieldSpec.name). Look values up by
    # `.id`, but render under the slug, which is what an ops file's `set:`
    # addresses.
    schema_ids = {f.id for f in schema_fields}

    lines: list = []
    # Schema-known fields first, in the form's own field order.
    for f in schema_fields:
        if f.id in data:
            rendered = _format_value(data[f.id])
            if rendered:
                lines.append(f"{f.name}: {rendered}")
    # Then leftover keys not named in the schema, alphabetically.
    for key in sorted(k for k in data.keys() if k not in schema_ids):
        rendered = _format_value(data[key])
        if rendered:
            lines.append(f"{key}: {rendered}")
    return lines


def render_values(tree: Tree, types: TypeSet, values: Values) -> bytes:
    # Depth from the parent chain, not from counting " > " in the path text —
    # a title that happens to contain that separator must not throw off
    # indentation.
    depth_of: dict = {}
    for node_id in tree.order:
        parent_id = tree.nodes[node_id].parent_id
        depth_of[node_id] = 0 if parent_id is None else depth_of[parent_id] + 1

    # Each line here already carries its full block-scalar indent (the base
    # "  " plus 2 per depth, from _depth_indent) — write these verbatim under
    # `tree: |`, don't indent them again.
    tree_lines: list = []
    for node_id in tree.order:
        node = tree.nodes[node_id]
        depth = depth_of[node_id]
        tree_lines.append(_depth_indent(depth) + _node_line(node, types))
        value_depth = depth + 1
        for line in _value_lines(node, types, values):
            tree_lines.append(_depth_indent(value_depth) + line)

    # These lines are NOT yet indented — they need the block-scalar's own
    # base indent added at assembly time.
    pictured_paths = [tree.nodes[nid].path for nid in tree.order if tree.nodes[nid].actor.picture]
    picture_lines = _PICTURES_HEADER.splitlines() + pictured_paths

    buf = [_HEADER.format(layer_id=tree.layer_id), "tree: |\n"]
    for line in tree_lines:
        buf.append(line + "\n")
    buf.append("\n")
    buf.append("pictures: |\n")
    for line in picture_lines:
        buf.append(("  " + line if line else "") + "\n")
    return "".join(buf).encode("utf-8")
