package graph

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// RenderTypesSchema renders types.schema.yaml: the dictionary behind every
// slug in the tree — field names, the Simulator field id each one writes to,
// and its type.
//
// The file is fully derived from the forms and is rewritten on every export,
// so it never drifts from the workspace. graph.values.yaml already carries the
// field names of the types it uses, so this file is for the write path: it is
// what turns a field name back into the Simulator id to write to.
func RenderTypesSchema(layerID string, types *TypeSet) ([]byte, error) {
	typesNode := &yaml.Node{Kind: yaml.MappingNode}
	for _, t := range types.Types {
		entry := &yaml.Node{Kind: yaml.MappingNode}
		if err := appendEntry(entry, "formId", t.FormID); err != nil {
			return nil, err
		}
		if t.FormTitle != "" {
			if err := appendEntry(entry, "form", t.FormTitle); err != nil {
				return nil, err
			}
		}
		if t.Description != "" {
			if err := appendEntry(entry, "description", oneLine(t.Description)); err != nil {
				return nil, err
			}
		}
		fields := &yaml.Node{Kind: yaml.MappingNode}
		for _, f := range t.Fields {
			spec, err := fieldSpecNode(f)
			if err != nil {
				return nil, err
			}
			fields.Content = append(fields.Content, scalar(0, f.Name), spec)
		}
		entry.Content = append(entry.Content, scalar(0, "fields"), fields)

		typesNode.Content = append(typesNode.Content, scalar(0, t.Slug), entry)
	}

	root := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = append(root.Content, scalar(0, "types"), typesNode)

	var body strings.Builder
	enc := yaml.NewEncoder(&body)
	// Two spaces per level, like every other YAML in this pipeline; the
	// encoder's own default is four.
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, fmt.Errorf("graph: marshal types schema: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("graph: marshal types schema: %w", err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Type dictionary for layer %s — generated by migration-factory-plugin-mcp (internal/graph).\n", layerID)
	b.WriteString("# Rewritten on every export: change the forms in Simulator, not this file.\n")
	b.WriteString("#\n")
	b.WriteString("#   slug      what the map addresses a type by; derived from the form title\n")
	b.WriteString("#   fields    <slug>: {id: <simulator field id>, type: ..., writable: bool}\n")
	b.WriteString("#   types     string | text | int | number | bool | date | enum[...] | ref(<slug>)\n")
	b.WriteString("\n")
	b.WriteString(body.String())
	return []byte(b.String()), nil
}

// fieldSpecNode renders one field as `{id: …, type: …}` on a single line. The
// key order is fixed here: a Go map would render alphabetically and put the
// title, the longest value, in front of the id.
func fieldSpecNode(f *FieldSpec) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	if err := appendEntry(node, "id", f.ID); err != nil {
		return nil, err
	}
	if err := appendEntry(node, "type", f.Type); err != nil {
		return nil, err
	}
	if !f.Writable {
		if err := appendEntry(node, "writable", false); err != nil {
			return nil, err
		}
	}
	if f.Title != "" {
		if err := appendEntry(node, "title", oneLine(f.Title)); err != nil {
			return nil, err
		}
	}
	return node, nil
}

// scalar builds a plain scalar node.
func scalar(style yaml.Style, value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value, Style: style}
}

// appendEntry appends a key and its encoded value to a mapping node.
func appendEntry(mapping *yaml.Node, key string, value any) error {
	var node yaml.Node
	if err := node.Encode(value); err != nil {
		return fmt.Errorf("graph: encode %s: %w", key, err)
	}
	mapping.Content = append(mapping.Content, scalar(0, key), &node)
	return nil
}

// ParseTypesSchema reads back what RenderTypesSchema wrote: the type
// dictionary, keyed by form id the way the write path needs it.
//
// It is the inverse of the renderer and exists for one reason — an export
// already paid for one GetForm per type, and re-reading fifty forms to apply
// three ops is the bulk of an apply's cost for none of its correctness. The
// dictionary is derived from forms that change rarely, and a stale entry
// fails loudly at validation (the field is simply not in the type) rather
// than writing something wrong.
func ParseTypesSchema(data []byte) (*TypeSet, error) {
	var doc struct {
		Types map[string]struct {
			FormID      int    `yaml:"formId"`
			Form        string `yaml:"form"`
			Description string `yaml:"description"`
			Fields      map[string]struct {
				ID       string `yaml:"id"`
				Type     string `yaml:"type"`
				Writable *bool  `yaml:"writable"`
				Title    string `yaml:"title"`
			} `yaml:"fields"`
		} `yaml:"types"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("graph: parse %s: %w", TypesFileName, err)
	}
	if len(doc.Types) == 0 {
		return nil, fmt.Errorf("graph: %s holds no types", TypesFileName)
	}

	ts := &TypeSet{byForm: make(map[int]*Type, len(doc.Types))}
	for slug, entry := range doc.Types {
		if entry.FormID <= 0 {
			return nil, fmt.Errorf("graph: type %q in %s has no formId", slug, TypesFileName)
		}
		t := &Type{
			Slug:        slug,
			FormID:      entry.FormID,
			FormTitle:   entry.Form,
			Description: entry.Description,
		}
		for name, f := range entry.Fields {
			t.Fields = append(t.Fields, &FieldSpec{
				Name: name,
				// A field with no id of its own is addressed by its name —
				// which is what the renderer writes when the two are equal.
				ID:       firstNonEmpty(f.ID, name),
				Type:     firstNonEmpty(f.Type, TypeString),
				Title:    f.Title,
				Writable: f.Writable == nil || *f.Writable,
			})
		}
		// YAML mappings decode in map order; the file's own order is the
		// form's, but it is lost here, so fields are sorted by name to keep
		// two plans of the same ops file identical.
		sort.Slice(t.Fields, func(i, j int) bool { return t.Fields[i].Name < t.Fields[j].Name })

		if first, dup := ts.byForm[t.FormID]; dup {
			return nil, fmt.Errorf("graph: %s maps form %d to both %q and %q",
				TypesFileName, t.FormID, first.Slug, slug)
		}
		ts.byForm[t.FormID] = t
		ts.Types = append(ts.Types, t)
	}
	sort.Slice(ts.Types, func(i, j int) bool { return ts.Types[i].FormID < ts.Types[j].FormID })
	ts.indexSlugs()
	return ts, nil
}

// LoadTypesSchema reads the type dictionary from a directory holding an
// export. It reports whether the file is there at all, so a caller can fall
// back to the form API without treating a missing file as a failure.
func LoadTypesSchema(dir string) (*TypeSet, bool, error) {
	data, err := os.ReadFile(filepath.Join(dirOrCwd(dir), TypesFileName))
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("graph: read %s: %w", TypesFileName, err)
	}
	ts, err := ParseTypesSchema(data)
	return ts, true, err
}
