package graph

import (
	"sort"
	"strings"
)

// ValuesFileName is the layer itself: the tree, and under every node the
// field values it carries. It is the one file an export is for — uuids live
// in the ids sidecar and Simulator field ids in the type schema, and neither
// belongs in front of a reader.
const ValuesFileName = "graph.values.yaml"

// RenderValues renders graph.values.yaml: the tree, with each node's values
// nested under it.
//
// Line grammar: <indent><label> [<type>], then optional "  # <description>",
// then one "<field>: <value>" line per filled field, indented one level
// deeper. Two spaces per level, and that indentation is the only
// representation of the hierarchy — uuids, positions, colors and the edge
// list are dropped. A node is addressed by any unique suffix of its path; the
// ids sidecar turns that back into a uuid.
//
// Field ids are stripped in favour of the schema name — a reader cannot use
// "item_17852806427596937" — and types.schema.yaml resolves both that name
// and the "[type]" on a node line back to what Simulator wants. The schema is
// not repeated here: on a sparsely filled layer it is more than half the
// file, and it is the same bytes twice. A value the schema does not know (a
// field left over from another form) keeps its raw key rather than being
// dropped.
func RenderValues(tree *Tree, types *TypeSet, values Values) []byte {
	var b strings.Builder
	b.WriteString("# generated by migration-factory-plugin-mcp (internal/graph) — do not edit by hand\n")
	b.WriteString("# the layer as a tree, with every field value under its node\n")
	b.WriteString("# addressing: any unique suffix of the path, separator \" > \"\n")
	b.WriteString("# to write back: an ops file of `at:` + `set:`/`rename:`, addressed the same\n")
	b.WriteString("# way — see " + OpsFileName + "; `make live-apply OPS=<file>` prints the diff\n")
	b.WriteString("# field names and [types]: see " + TypesFileName + "\n")
	b.WriteString("# `pictures:` after the tree lists the nodes that already carry an image\n")
	b.WriteString("layer: " + tree.LayerID + "\n\n")

	b.WriteString("tree: |\n")
	for _, n := range tree.Nodes {
		b.WriteString(indent(n.Depth) + treeLine(n, types) + "\n")
		for _, line := range valueLines(n, types, values) {
			b.WriteString(indent(n.Depth+1) + line + "\n")
		}
	}

	b.WriteString("\n")
	b.WriteString(renderPictures(tree))
	return []byte(b.String())
}

// renderPictures lists the nodes that already carry an image, by full path.
//
// It is a block of its own rather than a mark on the node's line: the line is
// what an `at:` address is read from, and a token nobody can address by does
// not belong on it. Written even when the list is empty, because "no node has
// a picture" and "this export predates the question" are different answers
// and only the first one is about the layer.
//
// A picture is a property of the actor and not a field of its form, so the
// tree — which renders form values — cannot carry it, and nothing else in the
// export would say which nodes still have a blank face.
func renderPictures(tree *Tree) string {
	var b strings.Builder
	b.WriteString("pictures: |\n")
	b.WriteString("  # nodes that already carry an image; every other node has none, and a run\n")
	b.WriteString("  # fills those and replaces none of these\n")
	for _, n := range tree.Nodes {
		if strings.TrimSpace(n.Actor.Picture) != "" {
			b.WriteString("  " + n.Path + "\n")
		}
	}
	return b.String()
}

// valueLines renders one node's values, schema fields first in form order and
// anything else after them, alphabetically.
func valueLines(n *Node, types *TypeSet, values Values) []string {
	vals := values[n.Actor.ID]
	if len(vals) == 0 {
		return nil
	}

	var lines []string
	named := make(map[string]bool, len(vals))
	if t, ok := types.Type(n.Actor.FormID); ok {
		for _, f := range t.Fields {
			v, present := vals[f.ID]
			if !present {
				continue
			}
			named[f.ID] = true
			if rendered := formatValue(v); rendered != "" {
				lines = append(lines, f.Name+": "+rendered)
			}
		}
	}

	var rest []string
	for key := range vals {
		if !named[key] {
			rest = append(rest, key)
		}
	}
	sort.Strings(rest)
	for _, key := range rest {
		if rendered := formatValue(vals[key]); rendered != "" {
			lines = append(lines, key+": "+rendered)
		}
	}
	return lines
}
